name = "eco-erp-system"
pages_build_output_dir = "dist"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "eco-core-db"
database_id = "d3db06c8-f790-45b3-8289-999240e158ee"

[[r2_buckets]]
binding = "DOCS_VAULT"
bucket_name = "eco-documents-vault"
